name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install libs
        run: |
          sudo apt install python2
          sudo apt install cmake
          sudo apt-get install libgtest-dev
          sudo apt-get install valgrind
          sudo apt-get install cppcheck
          sudo apt install python3-pip
          pip3 install gcovr
          sudo apt install gcovr
      - name: build
        run: |
          cd untitled
          mkdir build
          cd build
          cmake ..
          make
      - name: linters
        run: |
          cd untitled
          ./linters/run.sh --local
      - name: gtests
        run: |
          cd untitled
          cd tests
          ./tests
      - name: valgrind
        run: |
          cd untitled
          cd tests
          valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no --error-exitcode=1  ./tests
      - name: gcovr
        run: |
          cd untitled
          gcovr -r .